### ISSUE TITLE
[OOB] No 'proxy' option found in the dropdown

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-cloud-tutorial-python-influxdb#7]
Hi, I ran through this tutorial. In the step 4.b, no 'proxy' option found in the Access dropdown list in HTTP setting.
<img width="1013" alt="screen shot 2018-07-03 at 10 45 29" src="https://user-images.githubusercontent.com/3761826/42194485-2161f1fa-7eaf-11e8-81fd-2903cc616dfe.png">

**Comment by mbartling** [comment]
This must have changed in the latest Grafana release. Default access should be fine.

**Comment by mbartling** [comment]
@coisme I went ahead and fixed the grafana version. Can you try again?

**Comment by coisme** [comment]
Now I can see the 'proxy' option!
